services:
  db:
    image: oscarfonts/h2:latest
    container_name: h2-db
    ports:
      - "1521:1521"  # JDBC TCP
      - "81:81"      # Depend de l'image
    volumes:
      - h2_data:/opt/h2-data
    environment:
      H2_OPTIONS: "-ifNotExists"

  app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db

volumes:
  h2_data:
